title: Github is easy to learn !
author: Sasha Gordon
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Check out Githubs new learning site. Take advantage of learning something new like I'm doing. You won't regret it. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
